#!/bin/sh
# shellcheck disable=SC2039
# SC2039: In POSIX sh, echo flags are undefined. We use ash which has
# TODO FIND OUT PUT EXT NAME to VAR in order to reuse

msg() {
	echo "com_rak_spectral_scan:"  "$@"
	logger -t com_rak_spectral_scan "$@"
}

msg "cleaning __pycache__ after removal"
# check if we could get package name from env
rm -rf /usr/bin/restify/wes-exts/com_rak_spectral_scan

msg "removing fe plugin entry"
msg "extension removed"

exit 0
